const PRODUCTS = [
  { id: 1, nombre: 'manzana', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 2, nombre: 'leche', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 3, nombre: 'huevo', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 4, nombre: 'carne de res', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 5, nombre: 'mantequilla', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 6, nombre: 'queso gd', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 7, nombre: 'yogurt', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 8, nombre: 'cereal zucaritas', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 9, nombre: 'cebolla', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 10, nombre: 'atun md.', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 11, nombre: 'arroz', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 12, nombre: 'galletas oreo peq.', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 13, nombre: 'aceite vegetal', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 14, nombre: 'chocolate ferrero pq', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 15, nombre: 'nutella gd', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 16, nombre: 'tilapia premium', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 17, nombre: 'helado napolitano', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 18, nombre: 'botella cola pepsi', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 19, nombre: 'jamon cerdo gd', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 20, nombre: 'carne molida gd', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 21, nombre: 'jugo naranja gd', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 22, nombre: 'banano', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 23, nombre: 'verde', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 24, nombre: 'galletas chocochip', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 25, nombre: 'chuletas ahumadas', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 26, nombre: 'queso cheddar pq', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 27, nombre: 'jugo manzana pq', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 29, nombre: 'salsa de tomate', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
  { id: 30, nombre: 'mayonesa', cantidad: 1, caloriasTotales: 50, detalle: {organico: true, peso: 200, porciones: 1, caloriasPorcion: 50 } },
];

module.exports = {
  PRODUCTS
};
